# Generated by Django 4.2 on 2023-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Date and time deleted at"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="photo",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date and time updated"
            ),
        ),
    ]
