# Generated by Django 4.2 on 2023-04-22 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0004_favorite"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favorite",
            new_name="Favorites",
        ),
    ]
