# Generated by Django 4.2 on 2023-04-27 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0005_rename_favorite_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorites",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_photo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="favorites",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited",
                to="gallery.photo",
                verbose_name="Публикация",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(upload_to="photos", verbose_name="Фото"),
        ),
    ]
