# Generated by Django 4.2 on 2023-04-28 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0007_alter_favorites_author_alter_favorites_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="user_favorites",
            field=models.ManyToManyField(
                related_name="user_favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранные фотографии",
            ),
        ),
        migrations.DeleteModel(
            name="Favorites",
        ),
    ]
