# Generated by Django 4.2 on 2023-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_alter_photo_photo"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorites", to="gallery.photo", verbose_name="Избранные"
            ),
        ),
    ]
