# Generated by Django 4.2 on 2023-04-22 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_favorites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="favorites",
        ),
    ]
